"""add_status_to_tasks

Revision ID: 9e159894f17d
Revises: 13707cb15658
Create Date: 2025-04-20 06:33:50.019480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e159894f17d'
down_revision: Union[str, None] = '13707cb15658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column(
        'status',
        sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
        nullable=False,
        server_default=sa.text("'PENDING'"),
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
